import sys
import os
import random

# Proje dizinini path'e ekle
sys.path.append(os.getcwd())

from database.base import get_session
from database.models.purchasing import Supplier, Currency


def create_real_suppliers():
    session = get_session()
    print("🚀 Gerçek Tedarikçi Veritabanı Oluşturuluyor (50+ Firma)...")

    # Gerçek Firma Listesi
    suppliers_data = [
        # --- 1. PVC HAMMADDE & KİMYASALLAR ---
        {
            "name": "Petkim Petrokimya Holding A.Ş.",
            "short_name": "Petkim",
            "city": "İzmir",
            "district": "Aliağa",
            "address": "Siteler Mah. Necmettin Giritlioğlu Cad. No:6/1 Aliağa",
            "phone": "+90 232 616 12 40",
            "email": "info@petkim.com.tr",
            "website": "www.petkim.com.tr",
            "tax_office": "Aliağa",
            "currency": "USD",
            "term": 30,
            "notes": "Türkiye'nin en büyük PVC reçine üreticisi. S65/S70 ana tedarikçi.",
        },
        {
            "name": "Plastay Kimya Endüstrisi A.Ş.",
            "short_name": "Plastay",
            "city": "Kocaeli",
            "district": "Dilovası",
            "address": "GEBKİM OSB Erol Kiresepi Cad. No:4",
            "phone": "+90 262 724 88 88",
            "email": "satis@plastay.com",
            "website": "www.plastay.com",
            "tax_office": "İlyasbey",
            "currency": "USD",
            "term": 45,
            "notes": "Yerli DOTP ve plastikleştirici üreticisi. Tanker bazlı alım.",
        },
        {
            "name": "Novachem Kimya San. Tic. A.Ş.",
            "short_name": "Novachem",
            "city": "Gaziantep",
            "district": "Şehitkamil",
            "address": "4. Organize Sanayi Bölgesi 83414 Nolu Cad. No:11",
            "phone": "+90 342 337 44 55",
            "email": "info@novachem.com.tr",
            "website": "www.novachem.com.tr",
            "tax_office": "Gazikent",
            "currency": "USD",
            "term": 60,
            "notes": "İthal PVC ve kimyasal katkı tedarikçisi.",
        },
        {
            "name": "GEC Kimya San. Tic. A.Ş.",
            "short_name": "GEC Kimya",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "İstanbul Deri OSB Yan Sanayi Cad. No:12",
            "phone": "+90 216 394 00 22",
            "email": "sales@geckimya.com",
            "website": "www.geckimya.com",
            "tax_office": "Tuzla",
            "currency": "EUR",
            "term": 45,
            "notes": "Stabilizatör ve özel kimyasallar.",
        },
        {
            "name": "Plastifay Kimya Endüstrisi A.Ş.",
            "short_name": "Plastifay",
            "city": "Kocaeli",
            "district": "Gebze",
            "address": "Güzeller OSB İnönü Mah. Farabi Cad. No:3",
            "phone": "+90 262 646 11 00",
            "email": "info@plastifay.com",
            "website": "www.plastifay.com",
            "tax_office": "Uluçınar",
            "currency": "USD",
            "term": 30,
            "notes": "DOTP ve DOA yağları.",
        },
        {
            "name": "Plastdepo Plastik Hammadde",
            "short_name": "Plastdepo",
            "city": "Ankara",
            "district": "Yenimahalle",
            "address": "İvedik OSB 1122. Cadde No:5",
            "phone": "+90 312 394 26 82",
            "email": "ankara@plastdepo.com",
            "website": "www.plastdepo.com.tr",
            "tax_office": "Ostim",
            "currency": "USD",
            "term": 15,
            "notes": "Hızlı hammadde temini, spot piyasa.",
        },
        {
            "name": "Linora Dış Ticaret Ltd. Şti.",
            "short_name": "Linora",
            "city": "İstanbul",
            "district": "Başakşehir",
            "address": "İkitelli OSB Mutfakçılar San. Sit. M1 Blok",
            "phone": "+90 212 485 50 50",
            "email": "info@linora.com.tr",
            "website": "www.linora.com.tr",
            "tax_office": "İkitelli",
            "currency": "USD",
            "term": 45,
            "notes": "Kore menşeli PVC reçine ithalatçısı.",
        },
        {
            "name": "Cey Kimya Sanayi ve Ticaret A.Ş.",
            "short_name": "Cey Kimya",
            "city": "Adana",
            "district": "Yüreğir",
            "address": "Hacı Sabancı OSB 2. Cadde No:8",
            "phone": "+90 322 394 33 00",
            "email": "info@ceykimya.com",
            "website": "www.ceykimya.com",
            "tax_office": "Yüreğir",
            "currency": "TRY",
            "term": 60,
            "notes": "Sıvı kimyasallar.",
        },
        # --- 2. MASTERBATCH (BOYA) ---
        {
            "name": "İlhan Plastik ve Kimya San. Tic.",
            "short_name": "İlhan Plastik",
            "city": "Adana",
            "district": "Sarıçam",
            "address": "Adana Hacı Sabancı OSB 24. Cad. No:5",
            "phone": "+90 322 394 44 44",
            "email": "info@ilhanplastik.com.tr",
            "website": "www.ilhanplastik.com.tr",
            "tax_office": "Sarıçam",
            "currency": "USD",
            "term": 45,
            "notes": "Beyaz ve dolgulu masterbatch.",
        },
        {
            "name": "Seta Kimya San. A.Ş.",
            "short_name": "Setakim",
            "city": "İstanbul",
            "district": "Esenyurt",
            "address": "Akçaburgaz Mah. 3022. Sok. No:4",
            "phone": "+90 212 886 66 77",
            "email": "info@setakim.com",
            "website": "www.setakim.com",
            "tax_office": "Esenyurt",
            "currency": "EUR",
            "term": 30,
            "notes": "Özel renk çalışmaları.",
        },
        {
            "name": "Akkim Kimya San. Tic. A.Ş.",
            "short_name": "Akkim",
            "city": "Yalova",
            "district": "Merkez",
            "address": "Taşköprü Mevkii P.K. 17",
            "phone": "+90 226 815 33 00",
            "email": "akkim@akkim.com.tr",
            "website": "www.akkim.com.tr",
            "tax_office": "Yalova",
            "currency": "USD",
            "term": 60,
            "notes": "Performans kimyasalları.",
        },
        {
            "name": "Elm Kimya Sanayi",
            "short_name": "Elm Kimya",
            "city": "Konya",
            "district": "Selçuklu",
            "address": "Konya OSB Evrenköy Cad. No:20",
            "phone": "+90 332 239 00 50",
            "email": "info@elmkimya.com",
            "website": "www.elmkimya.com",
            "tax_office": "Mevlana",
            "currency": "TRY",
            "term": 45,
            "notes": "Renkli masterbatch.",
        },
        {
            "name": "Deka Boya San. Tic. A.Ş.",
            "short_name": "Sandeco",
            "city": "Kocaeli",
            "district": "Gebze",
            "address": "Mermerciler Sanayi Sitesi 34. Cad. No:3",
            "phone": "+90 262 728 10 10",
            "email": "info@sandeco.com.tr",
            "website": "www.sandeco.com.tr",
            "tax_office": "Gebze",
            "currency": "TRY",
            "term": 60,
            "notes": "Boya pigmentleri.",
        },
        {
            "name": "Yıldız Kolor Masterbatch",
            "short_name": "Yıldız Kolor",
            "city": "İstanbul",
            "district": "Bayrampaşa",
            "address": "Terazidere Mah. Güneş Cad. No:12",
            "phone": "+90 212 567 89 00",
            "email": "satis@yildizkolor.com",
            "website": "www.yildizkolor.com",
            "tax_office": "Bayrampaşa",
            "currency": "TRY",
            "term": 30,
            "notes": "Ekonomik siyah masterbatch.",
        },
        # --- 3. AMBALAJ & MASURA (Karton/Koli) ---
        {
            "name": "Kervancı Bobin Ambalaj San. A.Ş.",
            "short_name": "Kervancı",
            "city": "Gaziantep",
            "district": "Şehitkamil",
            "address": "5. OSB 83569 Nolu Cadde No:10",
            "phone": "+90 342 337 40 23",
            "email": "info@kervancibobin.com",
            "website": "www.kervancibobin.com",
            "tax_office": "Gaziantep",
            "currency": "TRY",
            "term": 60,
            "notes": "Yüksek tonajlı karton masura tedariği (Jumbo ve Makine tipi).",
        },
        {
            "name": "Diriliş Masura Ambalaj",
            "short_name": "Diriliş Masura",
            "city": "İstanbul",
            "district": "Sultanbeyli",
            "address": "Akşemsettin Mah. Su Kenarı Cad. No:41/A",
            "phone": "+90 216 426 26 24",
            "email": "dirilisambalaj@gmail.com",
            "website": "www.dirilismasuraambalaj.com",
            "tax_office": "Sultanbeyli",
            "currency": "TRY",
            "term": 30,
            "notes": "Hızlı teslimat, el tipi masura.",
        },
        {
            "name": "Onbey Kağıt Masura",
            "short_name": "Onbey Kağıt",
            "city": "İstanbul",
            "district": "Sultanbeyli",
            "address": "Adil Mah. Başak Sok. No:4/1",
            "phone": "+90 216 661 03 28",
            "email": "satis@onbeykagit.com",
            "website": "www.onbeykagit.com",
            "tax_office": "Sultanbeyli",
            "currency": "TRY",
            "term": 30,
            "notes": "Karton rolik ve boru.",
        },
        {
            "name": "Akay Oluklu Mukavva A.Ş.",
            "short_name": "Akay Kutu",
            "city": "Kayseri",
            "district": "Melikgazi",
            "address": "OSB 6. Cadde No:15",
            "phone": "+90 352 321 11 22",
            "email": "info@akayoluklu.com.tr",
            "website": "www.akayoluklu.com.tr",
            "tax_office": "Erciyes",
            "currency": "TRY",
            "term": 45,
            "notes": "Baskılı koli tedariği.",
        },
        {
            "name": "Akgül Ambalaj Sanayi",
            "short_name": "Akgül",
            "city": "İstanbul",
            "district": "Hadımköy",
            "address": "Atatürk Sanayi Bölgesi Ömerli Mah. No:20",
            "phone": "+90 212 771 20 20",
            "email": "info@akgulambalaj.com",
            "website": "www.akgulambalaj.com",
            "tax_office": "Büyükçekmece",
            "currency": "TRY",
            "term": 45,
            "notes": "Streç kutuları ve koliler.",
        },
        {
            "name": "Aktif Yazılım ve Matbaa",
            "short_name": "Aktif Etiket",
            "city": "İstanbul",
            "district": "Topkapı",
            "address": "2. Matbaacılar Sitesi D Blok No:12",
            "phone": "+90 212 501 22 33",
            "email": "siparis@aktifmatbaa.com",
            "website": "www.aktifmatbaa.com",
            "tax_office": "Topkapı",
            "currency": "TRY",
            "term": 15,
            "notes": "Termal etiket ve barkod ürünleri.",
        },
        {
            "name": "AC Etiket Ambalaj A.Ş.",
            "short_name": "AC Etiket",
            "city": "Bursa",
            "district": "Nilüfer",
            "address": "NOSAB N.115 Sok. No:4",
            "phone": "+90 224 411 00 11",
            "email": "info@acetiket.com",
            "website": "www.acetiket.com",
            "tax_office": "Çekirge",
            "currency": "TRY",
            "term": 30,
            "notes": "Rulo etiket.",
        },
        # --- 4. MAKİNE & YEDEK PARÇA & BAKIM ---
        {
            "name": "Hürteknik Makina",
            "short_name": "Hürteknik",
            "city": "İstanbul",
            "district": "Esenyurt",
            "address": "Akçaburgaz Mah. 120. Sok. No:15",
            "phone": "+90 554 624 10 56",
            "email": "info@hurteknikmakina.com",
            "website": "hurteknikmakina.com",
            "tax_office": "Esenyurt",
            "currency": "USD",
            "term": 0,
            "notes": "Streç sarma ve aktarma makineleri, yedek parça.",
        },
        {
            "name": "Pakmak Ambalaj Makinaları",
            "short_name": "Pakmak",
            "city": "İstanbul",
            "district": "Bağcılar",
            "address": "İstoç Ticaret Merkezi 10. Ada No:55",
            "phone": "+90 212 659 49 91",
            "email": "info@pakmak.com",
            "website": "www.pakmakambalaj.com",
            "tax_office": "Güneşli",
            "currency": "EUR",
            "term": 15,
            "notes": "Paketleme makinaları teknik servis ve parça.",
        },
        {
            "name": "Sand Industry Otomasyon",
            "short_name": "Sand Industry",
            "city": "Kocaeli",
            "district": "Başiskele",
            "address": "Sahil Mah. Çağla Sk. No:6",
            "phone": "+90 262 343 20 20",
            "email": "info@sand.com.tr",
            "website": "www.sand.com.tr",
            "tax_office": "Alemdar",
            "currency": "EUR",
            "term": 30,
            "notes": "Eriyik basınç sensörleri (Melt Pressure) ve otomasyon.",
        },
        {
            "name": "Apaydın Rezistans Isı Sanayi",
            "short_name": "Apaydın Isı",
            "city": "İstanbul",
            "district": "Bayrampaşa",
            "address": "Rami Kışla Cad. Topçular İş Merk. No:88",
            "phone": "+90 212 567 10 20",
            "email": "info@apaydinrezistans.com",
            "website": "www.apaydinrezistans.com",
            "tax_office": "Bayrampaşa",
            "currency": "TRY",
            "term": 15,
            "notes": "Seramik kovan rezistansları ve fişek rezistanslar.",
        },
        {
            "name": "Mertsan Tekstil ve Ambalaj Mak.",
            "short_name": "Mertsan",
            "city": "Gaziantep",
            "district": "Şahinbey",
            "address": "Küsget Sanayi Sitesi B Blok No:45",
            "phone": "+90 342 235 15 15",
            "email": "info@mertsanmakina.com",
            "website": "www.mertsanmakina.com",
            "tax_office": "Şahinbey",
            "currency": "TRY",
            "term": 30,
            "notes": "Yerli makine imalatçısı.",
        },
        {
            "name": "NMT Otomasyon Sistemleri",
            "short_name": "NMT",
            "city": "İzmir",
            "district": "Çiğli",
            "address": "AOSB 10006 Sok. No:12",
            "phone": "+90 232 376 80 80",
            "email": "info@nmtotomasyon.com",
            "website": "www.nmtotomasyon.com",
            "tax_office": "Çiğli",
            "currency": "EUR",
            "term": 30,
            "notes": "Sürücü ve PLC yedek parçaları.",
        },
        # --- 5. EK FİRMALAR (Listeyi tamamlamak için) ---
        {
            "name": "ABM Ambalaj Basım Merkezi",
            "short_name": "ABM",
            "city": "İstanbul",
            "district": "Maltepe",
            "address": "Başıbüyük Yolu No:10",
            "currency": "TRY",
            "term": 45,
            "notes": "Kutu basım.",
        },
        {
            "name": "AHS Yılmaz Matbaacılık",
            "short_name": "AHS Yılmaz",
            "city": "Ankara",
            "district": "Ostim",
            "address": "Ostim OSB 12. Cadde",
            "currency": "TRY",
            "term": 30,
            "notes": "Matbaa işleri.",
        },
        {
            "name": "Akon Rulo Kağıt A.Ş.",
            "short_name": "Akon Rulo",
            "city": "Tekirdağ",
            "district": "Çorlu",
            "address": "Türkgücü OSB Yılmaz Alpaslan Cad.",
            "currency": "TRY",
            "term": 60,
            "notes": "Kağıt rulo hammadde.",
        },
        {
            "name": "Pada Makine Sanayi",
            "short_name": "Pada",
            "city": "Bursa",
            "district": "Nilüfer",
            "address": "Beşevler Sanayi Sitesi",
            "currency": "TRY",
            "term": 30,
            "notes": "Mekanik bakım.",
        },
        {
            "name": "Özka Makina Otomasyon",
            "short_name": "Özka",
            "city": "İstanbul",
            "district": "Pendik",
            "address": "Sanayi Mah. Ensar Sok.",
            "currency": "TRY",
            "term": 15,
            "notes": "Sargı makineleri.",
        },
        {
            "name": "Hilal Makina İmalat",
            "short_name": "Hilal Makina",
            "city": "Konya",
            "district": "Karatay",
            "address": "Büsan Özel OSB",
            "currency": "TRY",
            "term": 45,
            "notes": "Metal işleme.",
        },
        {
            "name": "Kuzeyglobal Makine",
            "short_name": "Kuzeyglobal",
            "city": "İstanbul",
            "district": "Beylikdüzü",
            "address": "Mermerciler San. Sit.",
            "currency": "USD",
            "term": 60,
            "notes": "Extruder ithalatı.",
        },
        {
            "name": "Potentia Kimya",
            "short_name": "Potentia",
            "city": "İstanbul",
            "district": "Ataşehir",
            "address": "Barbaros Mah. Lale Sok.",
            "currency": "USD",
            "term": 30,
            "notes": "Polimer katkıları.",
        },
        {
            "name": "Potens Yapı Kimyasalları",
            "short_name": "Potens",
            "city": "İstanbul",
            "district": "Ümraniye",
            "address": "Şerifali Mah. Turgut Özal Bulv.",
            "currency": "TRY",
            "term": 45,
            "notes": "Yapı kimyasalları.",
        },
        {
            "name": "Klineks Kimya",
            "short_name": "Klineks",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "Birlik OSB",
            "currency": "TRY",
            "term": 30,
            "notes": "Endüstriyel temizlik kimyasalları.",
        },
        {
            "name": "Desi Kimya Madencilik",
            "short_name": "Desi Kimya",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "Deri OSB",
            "currency": "USD",
            "term": 30,
            "notes": "Nem alıcı paketler.",
        },
        {
            "name": "Renk Master Plastik",
            "short_name": "Renk Master",
            "city": "Gaziantep",
            "district": "Şehitkamil",
            "address": "2. OSB",
            "currency": "USD",
            "term": 60,
            "notes": "Gaziantep bölge tedarikçisi.",
        },
        {
            "name": "Emay Plastik Kalıp",
            "short_name": "Emay",
            "city": "Eskişehir",
            "district": "Odunpazarı",
            "address": "Teksan Sanayi Sitesi",
            "currency": "TRY",
            "term": 30,
            "notes": "Plastik enjeksiyon parçalar.",
        },
        {
            "name": "Anot Makina A.Ş.",
            "short_name": "Anot",
            "city": "Eskişehir",
            "district": "Tepebaşı",
            "address": "Eskişehir OSB",
            "currency": "EUR",
            "term": 45,
            "notes": "Otomasyon panoları.",
        },
        {
            "name": "Kafaoğlu Plastik A.Ş.",
            "short_name": "Kafaoğlu",
            "city": "Eskişehir",
            "district": "OSB",
            "address": "12. Cadde",
            "currency": "TRY",
            "term": 45,
            "notes": "Plastik sarf malzemeler.",
        },
        {
            "name": "Akfleks Kağıt Reklam",
            "short_name": "Akfleks",
            "city": "İstanbul",
            "district": "Kağıthane",
            "address": "Cendere Yolu",
            "currency": "TRY",
            "term": 30,
            "notes": "Reklam ve ambalaj kağıtları.",
        },
        {
            "name": "Akyıldız Ambalaj",
            "short_name": "Akyıldız",
            "city": "İstanbul",
            "district": "Zeytinburnu",
            "address": "Demirciler Sitesi",
            "currency": "TRY",
            "term": 15,
            "notes": "Naylon ve poşet.",
        },
        {
            "name": "Dicle Kimya Ticaret",
            "short_name": "Dicle Kimya",
            "city": "İstanbul",
            "district": "Maslak",
            "address": "Maslak 42 Plaza",
            "currency": "USD",
            "term": 45,
            "notes": "Solvent ve inceltici ticareti.",
        },
        {
            "name": "Genaş Gen Boya",
            "short_name": "Genaş",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "Kimyacılar OSB",
            "currency": "TRY",
            "term": 60,
            "notes": "Zemin boyaları.",
        },
        {
            "name": "Ed Strafor Yapı",
            "short_name": "Ed Strafor",
            "city": "Elazığ",
            "district": "Merkez",
            "address": "Akçakiraz",
            "currency": "TRY",
            "term": 30,
            "notes": "Koruyucu köpük ambalaj.",
        },
        {
            "name": "Aypol Solvent Kimya",
            "short_name": "Aypol",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "KOSB Melek Aras Bulv.",
            "currency": "USD",
            "term": 30,
            "notes": "Kimyasal hammadde.",
        },
        {
            "name": "SASA Polyester A.Ş.",
            "short_name": "SASA",
            "city": "Adana",
            "district": "Seyhan",
            "address": "Turhan Cemal Beriker Bulv.",
            "currency": "USD",
            "term": 60,
            "notes": "Polyester ve elyaf devi.",
        },
        {
            "name": "Fengbai Plastik",
            "short_name": "Fengbai",
            "city": "Yurtdışı",
            "district": "Çin",
            "address": "Zhengzhou City",
            "currency": "USD",
            "term": 90,
            "notes": "Global PVC reçine tedarikçisi.",
        },
        {
            "name": "Chemate Group",
            "short_name": "Chemate",
            "city": "Yurtdışı",
            "district": "Çin",
            "address": "Zhengzhou",
            "currency": "USD",
            "term": 90,
            "notes": "Kimyasal distribütörü.",
        },
        {
            "name": "Emrah Baygin Parkim",
            "short_name": "Parkim",
            "city": "İstanbul",
            "district": "Kadıköy",
            "address": "Bağdat Caddesi",
            "currency": "TRY",
            "term": 30,
            "notes": "Özel kimyasallar.",
        },
        {
            "name": "Mks Devo Chemicals",
            "short_name": "Mks Devo",
            "city": "İstanbul",
            "district": "Tuzla",
            "address": "Birlik OSB",
            "currency": "EUR",
            "term": 45,
            "notes": "Tekstil ve plastik kimyasalları.",
        },
    ]

    count = 0
    for s_data in suppliers_data:
        # Kod oluştur (Örn: SUP-PETKIM-001)
        short_code = s_data["short_name"].upper().replace(" ", "").replace(".", "")[:4]
        code = f"SUP-{short_code}-{random.randint(100,999)}"

        # Vergi No üret
        tax_no = str(random.randint(1000000000, 9999999999))
        if not s_data.get("tax_office"):
            s_data["tax_office"] = "Merkez"

        existing = (
            session.query(Supplier).filter(Supplier.name == s_data["name"]).first()
        )

        if not existing:
            new_sup = Supplier(
                code=code,
                name=s_data["name"],
                short_name=s_data["short_name"],
                tax_number=tax_no,
                tax_office=s_data["tax_office"],
                city=s_data["city"],
                district=s_data.get("district", "Merkez"),
                address=s_data["address"],
                phone=s_data.get("phone"),
                email=s_data.get("email"),
                website=s_data.get("website"),
                currency=s_data.get("currency", "TRY"),
                payment_term_days=s_data.get("term", 30),
                notes=s_data.get("notes"),
            )
            session.add(new_sup)
            count += 1
            if count % 10 == 0:
                print(f"✅ {count} tedarikçi eklendi...")

    try:
        session.commit()
        print(f"\n🎉 İşlem Tamamlandı! Toplam {count} yeni tedarikçi eklendi.")
    except Exception as e:
        session.rollback()
        print(f"\n❌ Hata: {str(e)}")
    finally:
        session.close()


if __name__ == "__main__":
    create_real_suppliers()
