"""add_personnel_tables

Revision ID: 0fccb7b94c4f
Revises: f774c2482f6e
Create Date: 2026-01-19 15:45:36.506064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fccb7b94c4f"
down_revision: Union[str, None] = "f774c2482f6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_entitlement_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "leave_type",
            sa.Enum(
                "ANNUAL",
                "SENIORITY",
                "MARRIAGE",
                "MATERNITY",
                "PATERNITY",
                "BEREAVEMENT",
                name="leaveentitlementtype",
            ),
            nullable=False,
        ),
        sa.Column("min_years", sa.Integer(), nullable=True),
        sa.Column("max_years", sa.Integer(), nullable=True),
        sa.Column("days_entitled", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leave_entitlement_rules", schema=None) as batch_op:
        batch_op.create_index("idx_rule_type", ["leave_type"], unique=False)

    op.create_table(
        "employee_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "CONTRACT",
                "ID_CARD",
                "DIPLOMA",
                "CERTIFICATE",
                "HEALTH_REPORT",
                "CRIMINAL_RECORD",
                "PHOTO",
                "OTHER",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "VALID", "EXPIRING_SOON", "EXPIRED", "MISSING", name="documentstatus"
            ),
            nullable=True,
        ),
        sa.Column("is_mandatory", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employee_documents", schema=None) as batch_op:
        batch_op.create_index("idx_doc_employee", ["employee_id"], unique=False)
        batch_op.create_index("idx_doc_expiry", ["expiry_date"], unique=False)
        batch_op.create_index("idx_doc_status", ["status"], unique=False)
        batch_op.create_index("idx_doc_type", ["document_type"], unique=False)

    op.create_table(
        "leave_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "leave_type",
            sa.Enum(
                "ANNUAL",
                "SENIORITY",
                "MARRIAGE",
                "MATERNITY",
                "PATERNITY",
                "BEREAVEMENT",
                name="leaveentitlementtype",
            ),
            nullable=False,
        ),
        sa.Column("carried_over", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("entitled", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("used", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pending", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leave_balances", schema=None) as batch_op:
        batch_op.create_index("idx_balance_employee", ["employee_id"], unique=False)
        batch_op.create_index("idx_balance_type", ["leave_type"], unique=False)
        batch_op.create_index("idx_balance_year", ["year"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("leave_balances", schema=None) as batch_op:
        batch_op.drop_index("idx_balance_year")
        batch_op.drop_index("idx_balance_type")
        batch_op.drop_index("idx_balance_employee")

    op.drop_table("leave_balances")
    with op.batch_alter_table("employee_documents", schema=None) as batch_op:
        batch_op.drop_index("idx_doc_type")
        batch_op.drop_index("idx_doc_status")
        batch_op.drop_index("idx_doc_expiry")
        batch_op.drop_index("idx_doc_employee")

    op.drop_table("employee_documents")
    with op.batch_alter_table("leave_entitlement_rules", schema=None) as batch_op:
        batch_op.drop_index("idx_rule_type")

    op.drop_table("leave_entitlement_rules")
    # ### end Alembic commands ###
