"""add_mrp_fields_to_items

Revision ID: 9f6a91342f90
Revises: 6aab869ba85c
Create Date: 2026-01-23 10:02:35.441158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f6a91342f90"
down_revision: Union[str, None] = "6aab869ba85c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum type explicitly for PostgreSQL
    sa.Enum("EXACT", "FIXED", "PERIOD", name="lotsizingprocedure").create(
        op.get_bind(), checkfirst=True
    )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lot_sizing_procedure",
                sa.Enum("EXACT", "FIXED", "PERIOD", name="lotsizingprocedure"),
                nullable=False,
                server_default="EXACT",
            )
        )
        batch_op.add_column(
            sa.Column("planning_time_fence", sa.Integer(), nullable=True)
        )

    # Remove server_default after adding column
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column("lot_sizing_procedure", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("planning_time_fence")
        batch_op.drop_column("lot_sizing_procedure")

    # Drop Enum type
    sa.Enum("EXACT", "FIXED", "PERIOD", name="lotsizingprocedure").drop(
        op.get_bind(), checkfirst=True
    )

    # ### end Alembic commands ###
