"""add_order_links_to_returns

Revision ID: ac67fe11a27e
Revises: fc19995711ad
Create Date: 2026-02-08 10:57:17.172825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac67fe11a27e'
down_revision: Union[str, None] = 'fc19995711ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=postgresql.ENUM('TRY', 'USD', 'EUR', 'GBP', name='currency'),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('return_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_sale_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_purchase_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_orders', ['related_purchase_order_id'], ['id'])
        batch_op.create_foreign_key(None, 'sales_orders', ['related_sale_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('related_purchase_order_id')
        batch_op.drop_column('related_sale_order_id')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('TRY', 'USD', 'EUR', 'GBP', name='currency'),
               existing_nullable=True)

    # ### end Alembic commands ###
