"""add specialized notes to work orders

Revision ID: d8a4eb1765f4
Revises: 20260112_001_add_shift_teams
Create Date: 2026-01-13 17:05:12.441920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8a4eb1765f4"
down_revision: Union[str, None] = "20260112_001_add_shift_teams"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("production_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("quality_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("shipping_notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_orders", schema=None) as batch_op:
        batch_op.drop_column("shipping_notes")
        batch_op.drop_column("quality_notes")
        batch_op.drop_column("production_notes")
    # ### end Alembic commands ###

    # ### end Alembic commands ###
