"""add_accounting_module

Revision ID: 404b8b172ca8
Revises: 008_add_purchase_invoice
Create Date: 2026-01-09 23:24:30.931729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "404b8b172ca8"
down_revision: Union[str, None] = "008_add_purchase_invoice"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "ASSET",
                "LIABILITY",
                "EQUITY",
                "REVENUE",
                "EXPENSE",
                "COST",
                name="accounttype",
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_detail", sa.Boolean(), nullable=True),
        sa.Column("opening_debit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("opening_credit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index("idx_account_parent", ["parent_id"], unique=False)
        batch_op.create_index("idx_account_type", ["account_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_accounts_code"), ["code"], unique=True)

    op.create_table(
        "fiscal_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["closed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fiscal_periods", schema=None) as batch_op:
        batch_op.create_index("idx_fiscal_year_month", ["year", "month"], unique=True)

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_no", sa.String(length=30), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("reference_no", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "POSTED", "CANCELLED", name="journalentrystatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("posted_by", sa.Integer(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_by", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index("idx_journal_date", ["entry_date"], unique=False)
        batch_op.create_index(
            "idx_journal_ref", ["reference_type", "reference_id"], unique=False
        )
        batch_op.create_index("idx_journal_status", ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_journal_entries_entry_no"), ["entry_no"], unique=True
        )

    op.create_table(
        "journal_entry_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journal_entry_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("line_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entry_lines", schema=None) as batch_op:
        batch_op.create_index("idx_jel_account", ["account_id"], unique=False)
        batch_op.create_index("idx_jel_entry", ["journal_entry_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal_entry_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_jel_entry")
        batch_op.drop_index("idx_jel_account")

    op.drop_table("journal_entry_lines")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entries_entry_no"))
        batch_op.drop_index("idx_journal_status")
        batch_op.drop_index("idx_journal_ref")
        batch_op.drop_index("idx_journal_date")

    op.drop_table("journal_entries")
    with op.batch_alter_table("fiscal_periods", schema=None) as batch_op:
        batch_op.drop_index("idx_fiscal_year_month")

    op.drop_table("fiscal_periods")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_code"))
        batch_op.drop_index("idx_account_type")
        batch_op.drop_index("idx_account_parent")

    op.drop_table("accounts")
    # ### end Alembic commands ###
