"""add_location_fields

Revision ID: 6be57edc6e91
Revises: 0a404c858c12
Create Date: 2026-01-18 13:52:01.827728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6be57edc6e91"
down_revision: Union[str, None] = "0a404c858c12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FK constraint ekleme - varsa atla
    try:
        with op.batch_alter_table("account_transactions", schema=None) as batch_op:
            batch_op.create_foreign_key(
                "fk_account_transactions_customer", "customers", ["customer_id"], ["id"]
            )
    except Exception:
        pass  # Zaten varsa atla

    # Index yeniden adlandırma işlemleri - zaten yapıldı, atla
    # (idx_mwo_* -> idx_wo_* dönüşümü önceki migration'da yapıldı)

    # Lokasyon alanları ekle
    with op.batch_alter_table("warehouse_locations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("barcode", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("zone", sa.String(length=50), nullable=True))
        batch_op.create_index("idx_location_barcode", ["barcode"], unique=False)
        batch_op.create_unique_constraint("uq_location_barcode", ["barcode"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse_locations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index("idx_location_barcode")
        batch_op.drop_column("zone")
        batch_op.drop_column("priority")
        batch_op.drop_column("barcode")

    with op.batch_alter_table("maintenance_work_orders", schema=None) as batch_op:
        batch_op.drop_index("idx_wo_status")
        batch_op.drop_index("idx_wo_equipment")
        batch_op.drop_index("idx_wo_assigned")
        batch_op.create_index(batch_op.f("idx_mwo_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_mwo_equipment"), ["equipment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_mwo_assigned"), ["assigned_to_id"], unique=False
        )

    with op.batch_alter_table("account_transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
