"""Add shipping module tables

Revision ID: 1ed6aaf7b6ba
Revises: 20260120_002_add_sscc_tables
Create Date: 2026-01-22 16:20:50.682533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed6aaf7b6ba'
down_revision: Union[str, None] = '20260120_002_add_sscc_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    paymenttype = postgresql.ENUM('pesin', 'vadeli', 'kapida', name='paymenttype', create_type=False)
    paymenttype.create(op.get_bind(), checkfirst=True)

    advancepaymentmethod = postgresql.ENUM('nakit', 'havale', 'kredi_karti', 'cek', name='advancepaymentmethod', create_type=False)
    advancepaymentmethod.create(op.get_bind(), checkfirst=True)

    shipmentreadiness = postgresql.ENUM('bekliyor', 'odeme', 'onay', 'stok', 'uretim', 'hazir', name='shipmentreadiness', create_type=False)
    shipmentreadiness.create(op.get_bind(), checkfirst=True)

    op.create_table('vehicles',
    sa.Column('plate_no', sa.String(length=15), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('tir', 'kamyon', 'kamyonet', 'panelvan', 'pickup', 'diger', name='vehicletype'), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capacity_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pallet_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'bakimda', 'pasif', name='vehiclestatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicle_status', ['status'], unique=False)
        batch_op.create_index('idx_vehicle_type', ['vehicle_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_no'), ['plate_no'], unique=True)

    op.create_table('drivers',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tc_no', sa.String(length=11), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('license_type', sa.String(length=10), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('src_no', sa.String(length=20), nullable=True),
    sa.Column('src_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('musait', 'gorevde', 'izinli', 'pasif', name='driverstatus'), nullable=True),
    sa.Column('default_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc_no')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index('idx_driver_license_expiry', ['license_expiry'], unique=False)
        batch_op.create_index('idx_driver_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_code'), ['code'], unique=True)

    op.create_table('shipments',
    sa.Column('shipment_no', sa.String(length=20), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planlandi', 'yukleniyor', 'yolda', 'teslim', 'iptal', name='shipmentstatus'), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_volume_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_pallets', sa.Integer(), nullable=True),
    sa.Column('route_order', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index('idx_shipment_date', ['shipment_date'], unique=False)
        batch_op.create_index('idx_shipment_driver', ['driver_id'], unique=False)
        batch_op.create_index('idx_shipment_status', ['status'], unique=False)
        batch_op.create_index('idx_shipment_vehicle', ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_no'), ['shipment_no'], unique=True)

    op.create_table('shipment_loads',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('transport_unit_id', sa.Integer(), nullable=False),
    sa.Column('load_sequence', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.Column('loaded_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_unit_id'], ['transport_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_loads', schema=None) as batch_op:
        batch_op.create_index('idx_sl_shipment', ['shipment_id'], unique=False)
        batch_op.create_index('idx_sl_transport_unit', ['transport_unit_id'], unique=False)

    op.create_table('order_advance_payments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', postgresql.ENUM('nakit', 'havale', 'kredi_karti', 'cek', name='advancepaymentmethod', create_type=False), nullable=True),
    sa.Column('reference_no', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_advance_payments', schema=None) as batch_op:
        batch_op.create_index('idx_oap_date', ['payment_date'], unique=False)
        batch_op.create_index('idx_oap_order', ['order_id'], unique=False)

    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.create_index('idx_si_delivery_note', ['delivery_note_id'], unique=False)
        batch_op.create_index('idx_si_shipment', ['shipment_id'], unique=False)

    # Note: maintenance_work_orders index changes skipped (already applied)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.Enum('pesin', 'vadeli', 'kapida', name='paymenttype'), nullable=True))
        batch_op.add_column(sa.Column('shipment_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipment_approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipment_approval_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipment_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requested_delivery_date', sa.Date(), nullable=True))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('backflush_mode',
               existing_type=postgresql.ENUM('ON_START', 'ON_COMPLETE', 'MANUAL', name='backflushmode'),
               nullable=False,
               existing_server_default=sa.text("'ON_START'::backflushmode"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('backflush_mode',
               existing_type=postgresql.ENUM('ON_START', 'ON_COMPLETE', 'MANUAL', name='backflushmode'),
               nullable=True,
               existing_server_default=sa.text("'ON_START'::backflushmode"))

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_column('requested_delivery_date')
        batch_op.drop_column('shipment_notes')
        batch_op.drop_column('shipment_approval_by')
        batch_op.drop_column('shipment_approval_date')
        batch_op.drop_column('shipment_approved')
        batch_op.drop_column('payment_type')

    # Note: maintenance_work_orders index changes skipped (already applied)

    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.drop_index('idx_si_shipment')
        batch_op.drop_index('idx_si_delivery_note')

    op.drop_table('shipment_items')
    with op.batch_alter_table('order_advance_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_oap_order')
        batch_op.drop_index('idx_oap_date')

    op.drop_table('order_advance_payments')
    with op.batch_alter_table('shipment_loads', schema=None) as batch_op:
        batch_op.drop_index('idx_sl_transport_unit')
        batch_op.drop_index('idx_sl_shipment')

    op.drop_table('shipment_loads')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_no'))
        batch_op.drop_index('idx_shipment_vehicle')
        batch_op.drop_index('idx_shipment_status')
        batch_op.drop_index('idx_shipment_driver')
        batch_op.drop_index('idx_shipment_date')

    op.drop_table('shipments')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_code'))
        batch_op.drop_index('idx_driver_status')
        batch_op.drop_index('idx_driver_license_expiry')

    op.drop_table('drivers')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_no'))
        batch_op.drop_index('idx_vehicle_type')
        batch_op.drop_index('idx_vehicle_status')

    op.drop_table('vehicles')
    # ### end Alembic commands ###
