"""add_company_tables

Revision ID: d1866c0535d6
Revises: 3239badfe24c
Create Date: 2026-01-19 09:07:44.412102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d1866c0535d6"
down_revision: Union[str, None] = "3239badfe24c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column(
            "company_type",
            sa.Enum(
                "ANONIM",
                "LIMITED",
                "SAHIS",
                "KOOPERATIF",
                "KAMU",
                "DIGER",
                name="companytype",
            ),
            nullable=True,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("foundation_date", sa.Date(), nullable=True),
        sa.Column("nace_code", sa.String(length=20), nullable=True),
        sa.Column("tax_country", sa.String(length=3), nullable=True),
        sa.Column("tax_office", sa.String(length=100), nullable=True),
        sa.Column("tax_number", sa.String(length=20), nullable=True),
        sa.Column("mersis_no", sa.String(length=20), nullable=True),
        sa.Column("trade_reg_no", sa.String(length=50), nullable=True),
        sa.Column("sgk_workplace", sa.String(length=30), nullable=True),
        sa.Column("kep_address", sa.String(length=255), nullable=True),
        sa.Column("is_efatura", sa.Boolean(), nullable=True),
        sa.Column("is_earsiv", sa.Boolean(), nullable=True),
        sa.Column("is_eirsaliye", sa.Boolean(), nullable=True),
        sa.Column("is_edefter", sa.Boolean(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("phone2", sa.String(length=20), nullable=True),
        sa.Column("fax", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index("idx_company_code", ["code"], unique=False)
        batch_op.create_index("idx_company_tax", ["tax_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_code"), ["code"], unique=True)

    op.create_table(
        "company_addresses",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "address_type",
            sa.Enum("MERKEZ", "FATURA", "SEVKIYAT", "SUBE", name="addresstype"),
            nullable=True,
        ),
        sa.Column("country", sa.String(length=3), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("district", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_addresses", schema=None) as batch_op:
        batch_op.create_index("idx_company_addr", ["company_id"], unique=False)

    op.create_table(
        "company_banks",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("branch", sa.String(length=100), nullable=True),
        sa.Column("account_holder", sa.String(length=255), nullable=True),
        sa.Column("iban", sa.String(length=34), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum("TRY", "USD", "EUR", "GBP", name="bankaccounttype"),
            nullable=True,
        ),
        sa.Column("swift_code", sa.String(length=11), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_banks", schema=None) as batch_op:
        batch_op.create_index("idx_company_bank", ["company_id"], unique=False)

    op.create_table(
        "company_contacts",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("mobile", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_contacts", schema=None) as batch_op:
        batch_op.create_index("idx_company_contact", ["company_id"], unique=False)

    op.create_table(
        "company_documents",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_documents", schema=None) as batch_op:
        batch_op.create_index(
            "idx_company_doc", ["company_id", "doc_type"], unique=False
        )

    op.create_table(
        "company_settings",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("date_format", sa.String(length=20), nullable=True),
        sa.Column("decimal_separator", sa.String(length=1), nullable=True),
        sa.Column("thousand_separator", sa.String(length=1), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("local_currency", sa.String(length=3), nullable=True),
        sa.Column("fiscal_year_start", sa.Integer(), nullable=True),
        sa.Column("fiscal_year_end", sa.Integer(), nullable=True),
        sa.Column("default_vat_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "default_withholding", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("accounting_plan", sa.String(length=50), nullable=True),
        sa.Column("rounding_rule", sa.String(length=20), nullable=True),
        sa.Column("invoice_prefix", sa.String(length=10), nullable=True),
        sa.Column("order_prefix", sa.String(length=10), nullable=True),
        sa.Column("delivery_prefix", sa.String(length=10), nullable=True),
        sa.Column("purchase_prefix", sa.String(length=10), nullable=True),
        sa.Column("default_warehouse_id", sa.Integer(), nullable=True),
        sa.Column("has_lot_tracking", sa.Boolean(), nullable=True),
        sa.Column("has_serial_tracking", sa.Boolean(), nullable=True),
        sa.Column("barcode_standard", sa.String(length=20), nullable=True),
        sa.Column(
            "production_type",
            sa.Enum("SIPARISE_URETIM", "STOKA_URETIM", "KARMA", name="productiontype"),
            nullable=True,
        ),
        sa.Column("work_calendar", sa.String(length=50), nullable=True),
        sa.Column("erp_uuid", sa.String(length=50), nullable=True),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column("efatura_integrator", sa.String(length=50), nullable=True),
        sa.Column("ecommerce_id", sa.String(length=100), nullable=True),
        sa.Column("sms_sender_id", sa.String(length=20), nullable=True),
        sa.Column("whatsapp_business", sa.String(length=20), nullable=True),
        sa.Column("backup_email", sa.String(length=255), nullable=True),
        sa.Column("user_limit", sa.Integer(), nullable=True),
        sa.Column("ip_restriction", sa.Text(), nullable=True),
        sa.Column("data_isolation", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_settings")
    with op.batch_alter_table("company_documents", schema=None) as batch_op:
        batch_op.drop_index("idx_company_doc")

    op.drop_table("company_documents")
    with op.batch_alter_table("company_contacts", schema=None) as batch_op:
        batch_op.drop_index("idx_company_contact")

    op.drop_table("company_contacts")
    with op.batch_alter_table("company_banks", schema=None) as batch_op:
        batch_op.drop_index("idx_company_bank")

    op.drop_table("company_banks")
    with op.batch_alter_table("company_addresses", schema=None) as batch_op:
        batch_op.drop_index("idx_company_addr")

    op.drop_table("company_addresses")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_code"))
        batch_op.drop_index("idx_company_tax")
        batch_op.drop_index("idx_company_code")

    op.drop_table("companies")
    # ### end Alembic commands ###
