"""Add payroll extended fields and status

Revision ID: 33c35b96877d
Revises: d1866c0535d6
Create Date: 2026-01-19 14:51:04.127626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33c35b96877d"
down_revision: Union[str, None] = "d1866c0535d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Önce enum tipini oluştur
    payrollstatus = postgresql.ENUM(
        "DRAFT", "CALCULATED", "APPROVED", "PAID", "CANCELLED", name="payrollstatus"
    )
    payrollstatus.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("payrolls", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("gross_salary", sa.Numeric(precision=15, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("sgk_employee", sa.Numeric(precision=15, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("sgk_employer", sa.Numeric(precision=15, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "unemployment_employee",
                sa.Numeric(precision=15, scale=2),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unemployment_employer",
                sa.Numeric(precision=15, scale=2),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("income_tax", sa.Numeric(precision=15, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("stamp_tax", sa.Numeric(precision=15, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "cumulative_tax_base", sa.Numeric(precision=18, scale=2), nullable=True
            )
        )
        batch_op.add_column(sa.Column("total_work_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("absent_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("late_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("overtime_hours", sa.Numeric(precision=6, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "DRAFT",
                    "CALCULATED",
                    "APPROVED",
                    "PAID",
                    "CANCELLED",
                    name="payrollstatus",
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("journal_entry_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))
        batch_op.create_index("idx_payroll_status", ["status"], unique=False)
        batch_op.create_index(
            "idx_payroll_unique",
            ["employee_id", "period_year", "period_month"],
            unique=True,
        )
        batch_op.create_foreign_key(
            None, "journal_entries", ["journal_entry_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "backflush_mode",
            existing_type=postgresql.ENUM(
                "ON_START", "ON_COMPLETE", "MANUAL", name="backflushmode"
            ),
            nullable=True,
            existing_server_default=sa.text("'ON_START'::backflushmode"),
        )

    with op.batch_alter_table("payrolls", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index("idx_payroll_unique")
        batch_op.drop_index("idx_payroll_status")
        batch_op.drop_column("notes")
        batch_op.drop_column("journal_entry_id")
        batch_op.drop_column("status")
        batch_op.drop_column("overtime_hours")
        batch_op.drop_column("late_count")
        batch_op.drop_column("absent_days")
        batch_op.drop_column("total_work_days")
        batch_op.drop_column("cumulative_tax_base")
        batch_op.drop_column("stamp_tax")
        batch_op.drop_column("income_tax")
        batch_op.drop_column("unemployment_employer")
        batch_op.drop_column("unemployment_employee")
        batch_op.drop_column("sgk_employer")
        batch_op.drop_column("sgk_employee")
        batch_op.drop_column("gross_salary")

    with op.batch_alter_table("maintenance_work_orders", schema=None) as batch_op:
        batch_op.drop_index("idx_wo_status")
        batch_op.drop_index("idx_wo_equipment")
        batch_op.drop_index("idx_wo_assigned")
        batch_op.create_index(batch_op.f("idx_mwo_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_mwo_equipment"), ["equipment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_mwo_assigned"), ["assigned_to_id"], unique=False
        )

    # ### end Alembic commands ###
