"""pro_phase_updates

Revision ID: 0a404c858c12
Revises: g7h8i9j0k1l2
Create Date: 2026-01-18 12:15:45.606990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a404c858c12"
down_revision: Union[str, None] = "g7h8i9j0k1l2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'downtimereason') THEN
            CREATE TYPE downtimereason AS ENUM ('BREAKDOWN', 'SETUP', 'MATERIAL_WAIT', 'OP_ABSENCE', 'POWER_FAILURE', 'MEAL_BREAK', 'QUALITY_ISSUE', 'OTHER');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'locationtype') THEN
            CREATE TYPE locationtype AS ENUM ('NORMAL', 'QUARANTINE', 'SCRAP', 'TRANSIT');
        END IF;
    END
    $$;
    """)
    op.create_table(
        "payrolls",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("overtime_pay", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("bonus", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("deductions", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("net_salary", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payrolls", schema=None) as batch_op:
        batch_op.create_index("idx_payroll_emp", ["employee_id"], unique=False)
        batch_op.create_index(
            "idx_payroll_period", ["period_year", "period_month"], unique=False
        )

    op.create_table(
        "production_downtimes",
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=True),
        sa.Column("work_station_id", sa.Integer(), nullable=False),
        sa.Column(
            "reason_code",
            postgresql.ENUM(
                "BREAKDOWN",
                "SETUP",
                "MATERIAL_WAIT",
                "OP_ABSENCE",
                "POWER_FAILURE",
                "MEAL_BREAK",
                "QUALITY_ISSUE",
                "OTHER",
                name="downtimereason",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["work_order_operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"], ["work_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_station_id"],
            ["work_stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("production_downtimes", schema=None) as batch_op:
        batch_op.create_index("idx_downtime_date", ["start_time"], unique=False)
        batch_op.create_index("idx_downtime_station", ["work_station_id"], unique=False)
        batch_op.create_index("idx_downtime_wo", ["work_order_id"], unique=False)

    with op.batch_alter_table("account_transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("purchase_invoice_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("journal_entry_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, "purchase_invoices", ["purchase_invoice_id"], ["id"]
        )
        batch_op.create_foreign_key(
            None, "journal_entries", ["journal_entry_id"], ["id"]
        )
    op.execute("ALTER TABLE attendances ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE employees ALTER COLUMN employment_type DROP DEFAULT")
    op.execute("ALTER TABLE leaves ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE purchase_invoices ALTER COLUMN currency DROP DEFAULT")
    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.alter_column(
            "check_in",
            existing_type=postgresql.TIME(),
            type_=sa.DateTime(),
            existing_nullable=True,
            postgresql_using="date + check_in",
        )
        batch_op.alter_column(
            "check_out",
            existing_type=postgresql.TIME(),
            type_=sa.DateTime(),
            existing_nullable=True,
            postgresql_using="date + check_out",
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                "PRESENT",
                "ABSENT",
                "LATE",
                "EARLY_LEAVE",
                "ON_LEAVE",
                "HOLIDAY",
                name="attendancestatus",
                create_type=False,
            ),
            existing_nullable=True,
            server_default=sa.text("'PRESENT'"),
            postgresql_using="UPPER(status)::attendancestatus",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.create_index("idx_att_date", ["date"], unique=False)
        batch_op.create_index("idx_att_emp", ["employee_id"], unique=False)
        batch_op.create_index("idx_att_emp_date", ["employee_id", "date"], unique=True)

    with op.batch_alter_table("audits", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "employees", ["auditor_id"], ["id"])

    with op.batch_alter_table("capas", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "employees", ["verified_by"], ["id"])
        batch_op.create_foreign_key(None, "employees", ["responsible_id"], ["id"])

    with op.batch_alter_table("customer_complaints", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])
        batch_op.create_foreign_key(None, "employees", ["assigned_to"], ["id"])

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.alter_column(
            "code", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=200), nullable=False
        )
        batch_op.alter_column(
            "phone",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=30),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "website",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=200),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.drop_constraint(
            batch_op.f("customers_company_name_key"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("idx_customers_code"))
        batch_op.create_index(batch_op.f("ix_customers_code"), ["code"], unique=True)
        batch_op.create_foreign_key(None, "price_lists", ["price_list_id"], ["id"])
        batch_op.drop_column("tax_id")
        batch_op.drop_column("status")
        batch_op.drop_column("company_name")
        batch_op.drop_column("sector")

    with op.batch_alter_table("dashboard_widgets", schema=None) as batch_op:
        batch_op.alter_column(
            "default_width",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "default_height",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "min_width",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "min_height",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "max_width",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("2"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "max_height",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("2"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "sort_order",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_system",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("false"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(batch_op.f("idx_dashboard_widget_code"))
        batch_op.create_index(
            batch_op.f("ix_dashboard_widgets_code"), ["code"], unique=True
        )

    with op.batch_alter_table("delivery_notes", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_constraint(batch_op.f("departments_code_key"), type_="unique")
        batch_op.create_index("idx_dept_code", ["code"], unique=False)
        batch_op.create_index("idx_dept_parent", ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_departments_code"), ["code"], unique=True)
        batch_op.create_foreign_key(
            None, "employees", ["manager_id"], ["id"], use_alter=True
        )
        batch_op.create_foreign_key(None, "departments", ["parent_id"], ["id"])

    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.alter_column(
            "gender",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum("MALE", "FEMALE", "OTHER", name="gender", create_type=False),
            existing_nullable=True,
            postgresql_using="UPPER(gender)::gender",
        )
        batch_op.alter_column(
            "hire_date",
            existing_type=sa.DATE(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_DATE"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "employment_type",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "CONTRACT",
                "INTERN",
                "TEMPORARY",
                name="employmenttype",
                create_type=False,
            ),
            existing_nullable=True,
            existing_server_default=sa.text("'full_time'::character varying"),  # type: ignore[arg-type]
            postgresql_using="UPPER(employment_type)::employmenttype",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_constraint(
            batch_op.f("employees_employee_no_key"), type_="unique"
        )
        batch_op.create_index("idx_emp_active", ["is_active"], unique=False)
        batch_op.create_index("idx_emp_dept", ["department_id"], unique=False)
        batch_op.create_index("idx_emp_name", ["first_name", "last_name"], unique=False)
        batch_op.create_index("idx_emp_no", ["employee_no"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_employees_employee_no"), ["employee_no"], unique=True
        )
        batch_op.create_foreign_key(None, "employees", ["manager_id"], ["id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    with op.batch_alter_table("equipment_downtimes", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("equipment_spare_parts", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_equipment_criticality", ["criticality"], unique=False
        )

    with op.batch_alter_table("inspections", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "employees", ["inspector_id"], ["id"])

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_qc_required", sa.Boolean(), nullable=True))

    with op.batch_alter_table("leaves", schema=None) as batch_op:
        batch_op.alter_column(
            "leave_type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum(
                "ANNUAL",
                "SICK",
                "MATERNITY",
                "PATERNITY",
                "MARRIAGE",
                "BEREAVEMENT",
                "UNPAID",
                "OTHER",
                name="leavetype",
                create_type=False,
            ),
            existing_nullable=False,
            postgresql_using="UPPER(leave_type)::leavetype",
        )
        batch_op.alter_column(
            "days",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=5, scale=1),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="leavestatus",
                create_type=False,
            ),
            existing_nullable=True,
            existing_server_default=sa.text("'pending'::character varying"),  # type: ignore[arg-type]
            postgresql_using="UPPER(status)::leavestatus",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.create_index(
            "idx_leave_dates", ["start_date", "end_date"], unique=False
        )
        batch_op.create_index("idx_leave_emp", ["employee_id"], unique=False)
        batch_op.create_index("idx_leave_status", ["status"], unique=False)

    with op.batch_alter_table("maintenance_checklist_items", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("maintenance_checklists", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )

    with op.batch_alter_table("maintenance_plans", schema=None) as batch_op:
        batch_op.create_index("idx_plan_equipment", ["equipment_id"], unique=False)
        batch_op.create_index(
            "idx_plan_next_date", ["next_maintenance_date"], unique=False
        )

    with op.batch_alter_table(
        "maintenance_request_attachments", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("maintenance_requests", schema=None) as batch_op:
        batch_op.create_index("idx_maint_req_date", ["request_date"], unique=False)

    with op.batch_alter_table("maintenance_work_orders", schema=None) as batch_op:
        batch_op.create_index("idx_mwo_assigned", ["assigned_to_id"], unique=False)
        batch_op.create_index("idx_mwo_equipment", ["equipment_id"], unique=False)
        batch_op.create_index("idx_mwo_status", ["status"], unique=False)

    with op.batch_alter_table("non_conformances", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "employees", ["assigned_to"], ["id"])
        batch_op.create_foreign_key(None, "employees", ["reported_by"], ["id"])

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_constraint(batch_op.f("positions_code_key"), type_="unique")
        batch_op.create_index("idx_pos_code", ["code"], unique=False)
        batch_op.create_index("idx_pos_dept", ["department_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_positions_code"), ["code"], unique=True)

    with op.batch_alter_table("purchase_invoice_items", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(batch_op.f("idx_purchase_invoice_item_invoice"))

    with op.batch_alter_table("purchase_invoices", schema=None) as batch_op:
        batch_op.alter_column(
            "currency",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                "TRY", "USD", "EUR", "GBP", name="currency", create_type=False
            ),
            existing_nullable=True,
            existing_server_default=sa.text("'TRY'::character varying"),  # type: ignore[arg-type]
            postgresql_using="UPPER(currency)::currency",
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(batch_op.f("idx_purchase_invoice_date"))
        batch_op.drop_index(batch_op.f("idx_purchase_invoice_no"))
        batch_op.drop_index(batch_op.f("idx_purchase_invoice_supplier"))
        batch_op.create_index(
            batch_op.f("ix_purchase_invoices_invoice_no"), ["invoice_no"], unique=True
        )

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("rotation_patterns", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(batch_op.f("idx_rotation_pattern_code"))
        batch_op.create_index("idx_rotation_pattern_code", ["code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rotation_patterns_code"), ["code"], unique=True
        )

    with op.batch_alter_table("rotation_schedules", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("sales_orders", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("sales_quotes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opportunity_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "customers", ["customer_id"], ["id"])
        batch_op.create_foreign_key(None, "opportunities", ["opportunity_id"], ["id"])

    with op.batch_alter_table("shift_teams", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(batch_op.f("idx_shift_team_code"))
        batch_op.create_index("idx_shift_team_code", ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_shift_teams_code"), ["code"], unique=True)

    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.alter_column("is_revoked", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_index(batch_op.f("idx_session_refresh"))
        batch_op.drop_index(batch_op.f("idx_session_token"))
        batch_op.create_index("idx_session_token", ["session_token"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_sessions_session_token"), ["session_token"], unique=True
        )
        batch_op.create_unique_constraint(None, ["refresh_token"])

    with op.batch_alter_table("warehouse_locations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "location_type",
                postgresql.ENUM(
                    "NORMAL",
                    "QUARANTINE",
                    "SCRAP",
                    "TRANSIT",
                    name="locationtype",
                    create_type=False,
                ),
                nullable=False,
                server_default="NORMAL",
            )
        )

    with op.batch_alter_table("work_order_attachments", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("work_order_checklist_results", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table(
        "work_order_operation_personnel", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "work_order_operation_personnel", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("work_order_checklist_results", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("work_order_attachments", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("warehouse_locations", schema=None) as batch_op:
        batch_op.drop_column("location_type")

    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_user_sessions_session_token"))
        batch_op.drop_index("idx_session_token")
        batch_op.create_index(
            batch_op.f("idx_session_token"), ["session_token"], unique=True
        )
        batch_op.create_index(
            batch_op.f("idx_session_refresh"), ["refresh_token"], unique=True
        )
        batch_op.alter_column("is_revoked", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("shift_teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shift_teams_code"))
        batch_op.drop_index("idx_shift_team_code")
        batch_op.create_index(batch_op.f("idx_shift_team_code"), ["code"], unique=True)
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("sales_quotes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("opportunity_id")

    with op.batch_alter_table("sales_orders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("rotation_schedules", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("rotation_patterns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rotation_patterns_code"))
        batch_op.drop_index("idx_rotation_pattern_code")
        batch_op.create_index(
            batch_op.f("idx_rotation_pattern_code"), ["code"], unique=True
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("purchase_invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_invoices_invoice_no"))
        batch_op.create_index(
            batch_op.f("idx_purchase_invoice_supplier"), ["supplier_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_purchase_invoice_no"), ["invoice_no"], unique=True
        )
        batch_op.create_index(
            batch_op.f("idx_purchase_invoice_date"), ["invoice_date"], unique=False
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "currency",
            existing_type=sa.Enum("TRY", "USD", "EUR", "GBP", name="currency"),
            type_=sa.VARCHAR(length=10),
            existing_nullable=True,
            existing_server_default=sa.text("'TRY'::character varying"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("purchase_invoice_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_purchase_invoice_item_invoice"),
            ["invoice_id"],
            unique=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_code"))
        batch_op.drop_index("idx_pos_dept")
        batch_op.drop_index("idx_pos_code")
        batch_op.create_unique_constraint(
            batch_op.f("positions_code_key"),
            ["code"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("non_conformances", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("maintenance_work_orders", schema=None) as batch_op:
        batch_op.drop_index("idx_mwo_status")
        batch_op.drop_index("idx_mwo_equipment")
        batch_op.drop_index("idx_mwo_assigned")

    with op.batch_alter_table("maintenance_requests", schema=None) as batch_op:
        batch_op.drop_index("idx_maint_req_date")

    with op.batch_alter_table(
        "maintenance_request_attachments", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("maintenance_plans", schema=None) as batch_op:
        batch_op.drop_index("idx_plan_next_date")
        batch_op.drop_index("idx_plan_equipment")

    with op.batch_alter_table("maintenance_checklists", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("maintenance_checklist_items", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("leaves", schema=None) as batch_op:
        batch_op.drop_index("idx_leave_status")
        batch_op.drop_index("idx_leave_emp")
        batch_op.drop_index("idx_leave_dates")
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING", "APPROVED", "REJECTED", "CANCELLED", name="leavestatus"
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
            existing_server_default=sa.text("'pending'::character varying"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "days",
            existing_type=sa.Numeric(precision=5, scale=1),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "leave_type",
            existing_type=sa.Enum(
                "ANNUAL",
                "SICK",
                "MATERNITY",
                "PATERNITY",
                "MARRIAGE",
                "BEREAVEMENT",
                "UNPAID",
                "OTHER",
                name="leavetype",
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("is_qc_required")

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("inspections", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.drop_index("idx_equipment_criticality")

    with op.batch_alter_table("equipment_spare_parts", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("equipment_downtimes", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_employees_employee_no"))
        batch_op.drop_index("idx_emp_no")
        batch_op.drop_index("idx_emp_name")
        batch_op.drop_index("idx_emp_dept")
        batch_op.drop_index("idx_emp_active")
        batch_op.create_unique_constraint(
            batch_op.f("employees_employee_no_key"),
            ["employee_no"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "employment_type",
            existing_type=sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "CONTRACT",
                "INTERN",
                "TEMPORARY",
                name="employmenttype",
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
            existing_server_default=sa.text("'full_time'::character varying"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "hire_date",
            existing_type=sa.DATE(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_DATE"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "gender",
            existing_type=sa.Enum("MALE", "FEMALE", "OTHER", name="gender"),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_departments_code"))
        batch_op.drop_index("idx_dept_parent")
        batch_op.drop_index("idx_dept_code")
        batch_op.create_unique_constraint(
            batch_op.f("departments_code_key"),
            ["code"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("delivery_notes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("dashboard_widgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_widgets_code"))
        batch_op.create_index(
            batch_op.f("idx_dashboard_widget_code"), ["code"], unique=True
        )
        batch_op.alter_column(
            "is_system",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("false"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "sort_order",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "max_height",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("2"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "max_width",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("2"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "min_height",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "min_width",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "default_height",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "default_width",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sector", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "company_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "status",
                sa.VARCHAR(length=20),
                server_default=sa.text("'Aday'::character varying"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "tax_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_customers_code"))
        batch_op.create_index(batch_op.f("idx_customers_code"), ["code"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("customers_company_name_key"),
            ["company_name"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "website",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "phone",
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=200), nullable=True
        )
        batch_op.alter_column(
            "code", existing_type=sa.VARCHAR(length=20), nullable=True
        )

    with op.batch_alter_table("customer_complaints", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("capas", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("audits", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("attendances", schema=None) as batch_op:
        batch_op.drop_index("idx_att_emp_date")
        batch_op.drop_index("idx_att_emp")
        batch_op.drop_index("idx_att_date")
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("true"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PRESENT",
                "ABSENT",
                "LATE",
                "EARLY_LEAVE",
                "ON_LEAVE",
                "HOLIDAY",
                name="attendancestatus",
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
            existing_server_default=sa.text("'present'::character varying"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "check_out",
            existing_type=sa.DateTime(),
            type_=postgresql.TIME(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "check_in",
            existing_type=sa.DateTime(),
            type_=postgresql.TIME(),
            existing_nullable=True,
        )

    with op.batch_alter_table("account_transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("journal_entry_id")
        batch_op.drop_column("purchase_invoice_id")

    with op.batch_alter_table("production_downtimes", schema=None) as batch_op:
        batch_op.drop_index("idx_downtime_wo")
        batch_op.drop_index("idx_downtime_station")
        batch_op.drop_index("idx_downtime_date")

    op.drop_table("production_downtimes")
    with op.batch_alter_table("payrolls", schema=None) as batch_op:
        batch_op.drop_index("idx_payroll_period")
        batch_op.drop_index("idx_payroll_emp")

    op.drop_table("payrolls")
    # ### end Alembic commands ###
