"""add_mrp_module

Revision ID: 5e189441534b
Revises: 404b8b172ca8
Create Date: 2026-01-09 23:41:47.671386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e189441534b"
down_revision: Union[str, None] = "404b8b172ca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mrp_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_no", sa.String(length=30), nullable=False),
        sa.Column("run_date", sa.DateTime(), nullable=True),
        sa.Column("planning_horizon_days", sa.Integer(), nullable=True),
        sa.Column("consider_safety_stock", sa.Boolean(), nullable=True),
        sa.Column("include_work_orders", sa.Boolean(), nullable=True),
        sa.Column("include_sales_orders", sa.Boolean(), nullable=True),
        sa.Column("item_filter", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "COMPLETED", "APPLIED", "CANCELLED", name="mrprunstatus"
            ),
            nullable=False,
        ),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("items_with_shortage", sa.Integer(), nullable=True),
        sa.Column("total_suggestions", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mrp_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mrp_runs_run_no"), ["run_no"], unique=True)

    op.create_table(
        "mrp_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mrp_run_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("requirement_date", sa.Date(), nullable=False),
        sa.Column(
            "gross_requirement", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column(
            "scheduled_receipts", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column(
            "projected_on_hand", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column("net_requirement", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "planned_order_receipt", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column(
            "planned_order_release", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column(
            "demand_source",
            sa.Enum(
                "WORK_ORDER", "SALES_ORDER", "MANUAL", "FORECAST", name="demandsource"
            ),
            nullable=True,
        ),
        sa.Column("demand_source_id", sa.Integer(), nullable=True),
        sa.Column("demand_source_ref", sa.String(length=50), nullable=True),
        sa.Column(
            "suggestion_type",
            sa.Enum("PURCHASE", "MANUFACTURE", name="suggestiontype"),
            nullable=True,
        ),
        sa.Column("suggested_qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("suggested_date", sa.Date(), nullable=True),
        sa.Column("is_applied", sa.Boolean(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("applied_order_type", sa.String(length=50), nullable=True),
        sa.Column("applied_order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(["mrp_run_id"], ["mrp_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mrp_lines", schema=None) as batch_op:
        batch_op.create_index("idx_mrpline_date", ["requirement_date"], unique=False)
        batch_op.create_index("idx_mrpline_item", ["item_id"], unique=False)
        batch_op.create_index("idx_mrpline_run", ["mrp_run_id"], unique=False)
        batch_op.create_index(
            "idx_mrpline_suggestion", ["suggestion_type", "is_applied"], unique=False
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("min_order_qty", sa.Numeric(precision=18, scale=4), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "order_multiple", sa.Numeric(precision=18, scale=4), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("procurement_type", sa.String(length=20), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("procurement_type")
        batch_op.drop_column("order_multiple")
        batch_op.drop_column("min_order_qty")

    with op.batch_alter_table("mrp_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_mrpline_suggestion")
        batch_op.drop_index("idx_mrpline_run")
        batch_op.drop_index("idx_mrpline_item")
        batch_op.drop_index("idx_mrpline_date")

    op.drop_table("mrp_lines")
    with op.batch_alter_table("mrp_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mrp_runs_run_no"))

    op.drop_table("mrp_runs")
    # ### end Alembic commands ###
