"""add_training_tables

Revision ID: f774c2482f6e
Revises: a860a91030cb
Create Date: 2026-01-19 15:39:59.580305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f774c2482f6e"
down_revision: Union[str, None] = "a860a91030cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "training_type",
            sa.Enum(
                "INTERNAL",
                "EXTERNAL",
                "ONLINE",
                "ON_THE_JOB",
                "CERTIFICATION",
                name="trainingtype",
            ),
            nullable=True,
        ),
        sa.Column("duration_hours", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("trainer_name", sa.String(length=200), nullable=True),
        sa.Column("training_provider", sa.String(length=200), nullable=True),
        sa.Column("cost", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("has_certificate", sa.Boolean(), nullable=True),
        sa.Column("certificate_validity_months", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="trainingstatus",
            ),
            nullable=True,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.create_index("idx_session_date", ["planned_date"], unique=False)
        batch_op.create_index("idx_session_status", ["status"], unique=False)
        batch_op.create_index("idx_session_training", ["training_id"], unique=False)

    op.create_table(
        "employee_certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issuing_authority", sa.String(length=200), nullable=True),
        sa.Column("certificate_number", sa.String(length=100), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "VALID", "EXPIRING_SOON", "EXPIRED", "RENEWED", name="certificatestatus"
            ),
            nullable=True,
        ),
        sa.Column("training_id", sa.Integer(), nullable=True),
        sa.Column("document_path", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employee_certificates", schema=None) as batch_op:
        batch_op.create_index("idx_cert_employee", ["employee_id"], unique=False)
        batch_op.create_index("idx_cert_expiry", ["expiry_date"], unique=False)
        batch_op.create_index("idx_cert_status", ["status"], unique=False)

    op.create_table(
        "training_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("attended", sa.Boolean(), nullable=True),
        sa.Column("attendance_hours", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("certificate_issued", sa.Boolean(), nullable=True),
        sa.Column("certificate_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_participants", schema=None) as batch_op:
        batch_op.create_index("idx_participant_employee", ["employee_id"], unique=False)
        batch_op.create_index("idx_participant_session", ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("training_participants", schema=None) as batch_op:
        batch_op.drop_index("idx_participant_session")
        batch_op.drop_index("idx_participant_employee")

    op.drop_table("training_participants")
    with op.batch_alter_table("employee_certificates", schema=None) as batch_op:
        batch_op.drop_index("idx_cert_status")
        batch_op.drop_index("idx_cert_expiry")
        batch_op.drop_index("idx_cert_employee")

    op.drop_table("employee_certificates")
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_session_training")
        batch_op.drop_index("idx_session_status")
        batch_op.drop_index("idx_session_date")

    op.drop_table("training_sessions")
    op.drop_table("trainings")
    # ### end Alembic commands ###
