"""Add shipment phase 2 columns

Revision ID: 6aab869ba85c
Revises: 1ed6aaf7b6ba
Create Date: 2026-01-22 20:52:59.971972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6aab869ba85c"
down_revision: Union[str, None] = "1ed6aaf7b6ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "freight_amount", sa.Numeric(precision=12, scale=2), nullable=True
            )
        )
        batch_op.add_column(sa.Column("currency", sa.String(length=3), nullable=True))
        batch_op.add_column(
            sa.Column("carrier_invoice_no", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("extra_costs", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("in_transit_warehouse_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "warehouses", ["in_transit_warehouse_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("in_transit_warehouse_id")
        batch_op.drop_column("extra_costs")
        batch_op.drop_column("carrier_invoice_no")
        batch_op.drop_column("currency")
        batch_op.drop_column("freight_amount")

    with op.batch_alter_table("maintenance_work_orders", schema=None) as batch_op:
        batch_op.drop_index("idx_wo_status")
        batch_op.drop_index("idx_wo_equipment")
        batch_op.drop_index("idx_wo_assigned")
        batch_op.create_index(batch_op.f("idx_mwo_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_mwo_equipment"), ["equipment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_mwo_assigned"), ["assigned_to_id"], unique=False
        )

    # ### end Alembic commands ###
