"""
Akıllı İş ERP - Konfigürasyon
"""

from .settings import (
    BASE_DIR,
    THEMES_DIR,
    ICONS_DIR,
    DATA_DIR,
    APP_NAME,
    APP_VERSION,
    APP_DESCRIPTION,
    DB_ENGINE,
    DB_HOST,
    DB_PORT,
    DB_NAME,
    DB_USER,
    DB_PASSWORD,
    get_database_url,
    DEBUG,
    SECRET_KEY,
    ANTHROPIC_API_KEY,
    AI_MODEL,
    UI,
    COLORS,
    LANGUAGE,
    DATE_FORMAT,
    DATETIME_FORMAT,
    CURRENCY,
    CURRENCY_SYMBOL,
)

from .themes import (
    Theme, 
    ThemeType, 
    ThemeManager, 
    get_theme, 
    get_colors,
    THEMES,
    DARK_THEME,
    MATERIAL_OCEAN_THEME,
)


__all__ = [
    # Settings
    "BASE_DIR",
    "THEMES_DIR",
    "ICONS_DIR",
    "DATA_DIR",
    "APP_NAME",
    "APP_VERSION",
    "APP_DESCRIPTION",
    "DB_ENGINE",
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DB_USER",
    "DB_PASSWORD",
    "get_database_url",
    "DEBUG",
    "SECRET_KEY",
    "ANTHROPIC_API_KEY",
    "AI_MODEL",
    "UI",
    "COLORS",
    "LANGUAGE",
    "DATE_FORMAT",
    "DATETIME_FORMAT",
    "CURRENCY",
    "CURRENCY_SYMBOL",
    # Themes
    "Theme",
    "ThemeType", 
    "ThemeManager",
    "get_theme",
    "get_colors",
    "THEMES",
    "DARK_THEME",
    "MATERIAL_OCEAN_THEME",
]
